on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test RustyHog action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rusty Hog action step
        uses: ./ # Uses an action in the root directory
        id: rustyhog
        with:
          shavalue: ${{ github.sha }}
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "${{ steps.rustyhog.outputs.jsonresult }}"
